name: PlayerLog
version: 1.3
main: com.Mooling0602.PlayerLog.LogInterceptor
api-version: 1.13
folia-supported: true
description: A plugin to intercept messages about player in-game.
author: Mooling0602
commands:
  chatmsg:
    description: 切换聊天日志拦截
    usage: /chatmsg {on|off}
  fakelog:
    description: 模拟服务端日志
    usage: /fakelog <info_message>